### PR TITLE
Code is not pure ES6

### PR DESCRIPTION
**Pull request by fregante**
The code can't be both "pure ES6" and typescript. Pure ES6 doesn't have types.

### CODE REVIEW

**Comment by jiayihu** [comment]
I mean that TS has been used only for types and more clarity, but I do not use language features not in standard stage4 Javascript like class fields, enums or so on. So if you understand ES6 and you have seen a typed languaged at least once in your life you're fine with understanding the code.

The purpose of that sentence is "do not be afraid to see Typescript files, it's Javascript yet". Since this repo should be interested also to entry-level devs I didn't want them to be afraid.

Of course if I forgot to remove some TS specific syntax, apart from types, feel free to let me know.

**Comment by bfred-it** [comment]
Yeah that's the issue:
- for entry-level devs 
- says it's javascript
- uses typescript syntax

It'd confuse the hell out of me if I saw `:` in the parameters list 😃

**Comment by jiayihu** [comment]
That was my fear in using TS for this project indeed 😄 But I find the typings are a big help in understanding code the first time. For instance It makes explicit that the result of some operation is a `Node` and when you work with it you can have only `parent`, `left`, `right` and `key` properties.

Also TS is far more popular than Flow and it's already familiar to people who knows C#. It's also similar to C++ (not sure for Java, since I never used it).

Maybe we could change the statement into `Implementations are in standard ES6 Javascript with the addition of Typescript type annotations for better clarity.`

**Comment by bfred-it** [comment]
As a JS developer I'd rather see the types as comments. I know this wouldn't help with your build but it'd help the noobs without TS knowledge.

**Comment by jiayihu** [comment]
I understand your point, but TS is not a debatable option at this stage.

I'll leave the PR open is anyone else is confused by the wording, which should be the focus of this PR.

**Comment by bfred-it** [comment]
This PR doesn't focus on the wording only, it was a tongue-in-cheek response to using TypeScript in a repo that would be good for JavaScript beginners.

**Comment by jiayihu** [comment]
As I said TS is not debatable at this point and there is no reason for a "TS vs JS" discussion here. I 
appreciate your opinion but I disagree in this specific case, since the usage of TS is only for typing and considering that many beginners come from C++, C# or Java.

Besides the repo is not only for JS beginners, although they surely are in the target, but also for anyone else who forgot the implementation of an algorithm and I believe TS would help in that. I'd even say it's not for very beginners since you must also know what unit tests are, how to run npm scripts and so on.

Thanks again for your time, I've closed the PR because I do not agree with its intention now that you have clarified it.

**Pull request closed without merging**
