### PR TITLE
created .gitignore file.

### PR DESCRIPTION
**Pull request by moeenz**
There was no `.gitignore` file present in project to deal with `node_modules` folder.

### CODE REVIEW

**Comment by jiayihu** [comment]
How strange I forgot this file! Anyway would you mind adding a more complete `.gitignore`, generated from https://www.gitignore.io ?

**Comment by moeenz** [comment]
No problem with a more general one, but there's nothing found on [https://www.gitignore.io/](https://www.gitignore.io/) for either JavaScript or TypeScript.

**Comment by jiayihu** [comment]
I usually enter the OS `Mac`, `Windows` and `Linux`

**Comment by moeenz** [comment]
There was no entry for JavaScript or TypeScript but the was for Node. Now the .gitignore contains ignore types for Node, Linux, Mac and Windows.

**Pull request merged**
